services:
  database:
    container_name: kanta
    image: postgres:18
    volumes:
      - db_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    ports:
      - "${PUBLIC_PG_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env

  database-migrations:
    image: flyway/flyway:latest
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./packages/backend/migrations:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate

  app:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"

volumes:
  db_data:
